"""Export user ``@tool`` extensions as an MCP server + register it in a project's mcp.yaml.

This lets a generated project's agentic backbone (or Claude Code / Cursor) call the
tools you wrote with ``@tool`` — they become first-class MCP tools.

    perfectrag export-tools --from ./extensions.py --project .

writes ``perfectrag_tools_server.py`` (a tiny FastMCP server) into the project and adds
a ``perfectrag-tools`` entry to ``mcp.yaml``. Pure tools run standalone; tools that take
``ctx`` are served against a RAG built from the project's ``perfectrag.yml``.
"""

from __future__ import annotations

import functools
import inspect
from pathlib import Path
from typing import Any

import yaml

SERVER_FILENAME = "perfectrag_tools_server.py"


def render_server_script(ext_files: list[str], config: str = "perfectrag.yml") -> str:
    """Render the standalone MCP server script (kept tiny — logic lives in `serve`)."""
    files_repr = ", ".join(repr(f) for f in ext_files)
    return (
        '"""Auto-generated by `perfectrag export-tools` — serves @tool extensions over MCP.\n'
        'Do not edit; re-run the command to regenerate."""\n'
        "from perfectrag.mcp_tools import serve\n\n"
        f"serve([{files_repr}], config={config!r})\n"
    )


def _exposed_callable(ext_obj: Any, rag: Any) -> Any | None:
    """Return a plain callable for an Extension, hiding `ctx` from the MCP schema.

    Pure tools are returned as-is. ctx-tools are bound to a Context built from `rag`
    (or skipped if no rag is available)."""
    if not ext_obj.wants_ctx:
        return ext_obj.fn
    if rag is None:
        return None
    ctx = rag._ctx()

    @functools.wraps(ext_obj.fn)
    def wrapper(**kwargs: Any) -> Any:
        return ext_obj.fn(ctx, **kwargs)

    # Strip `ctx` from the signature + annotations so MCP sees only real args.
    sig = inspect.signature(ext_obj.fn)
    params = [p for n, p in sig.parameters.items() if n not in ("ctx", "context")]
    wrapper.__signature__ = sig.replace(parameters=params)  # type: ignore[attr-defined]
    wrapper.__annotations__ = {
        k: v for k, v in getattr(ext_obj.fn, "__annotations__", {}).items()
        if k not in ("ctx", "context")
    }
    return wrapper


def build_server(mcp: Any, ext_files: list[str], *, config: str | None = None,
                 rag: Any = None) -> list[str]:
    """Load extensions and register every ``@tool`` onto an MCP-like object.

    `mcp` only needs a FastMCP-compatible ``.tool(name=..., description=...)`` decorator.
    Returns the names registered. Separated from `serve` so it's testable without fastmcp.
    """
    from perfectrag.core import extensions as ext

    for f in ext_files:
        ext.load_extensions(f)
    if rag is None and config and Path(config).exists():
        try:
            from perfectrag.core import RAG
            rag = RAG.from_config(config)
        except Exception:
            rag = None

    registered: list[str] = []
    for e in ext.REGISTRY.all(ext.TOOL):
        fn = _exposed_callable(e, rag)
        if fn is None:
            continue  # ctx-tool with no RAG to bind to — skip
        mcp.tool(name=e.name, description=e.description)(fn)
        registered.append(e.name)
    return registered


def serve(ext_files: list[str], config: str = "perfectrag.yml") -> None:  # pragma: no cover
    """Run a FastMCP server exposing the @tool extensions (blocks)."""
    try:
        from fastmcp import FastMCP
    except ImportError as exc:
        raise SystemExit(
            "perfectRAG tools MCP server needs FastMCP. Install it:\n  pip install fastmcp"
        ) from exc
    mcp = FastMCP("perfectrag-tools")
    build_server(mcp, ext_files, config=config)
    mcp.run()


def export_tools_to_mcp(project_dir: str | Path, ext_files: list[str],
                        config: str = "perfectrag.yml") -> Path:
    """Write the server script + splice a ``perfectrag-tools`` entry into mcp.yaml.

    Returns the path to the updated mcp.yaml."""
    project = Path(project_dir)
    project.mkdir(parents=True, exist_ok=True)
    (project / SERVER_FILENAME).write_text(
        render_server_script(ext_files, config), encoding="utf-8"
    )
    mcp_path = project / "mcp.yaml"
    data = (yaml.safe_load(mcp_path.read_text(encoding="utf-8")) or {}) if mcp_path.exists() else {}
    data.setdefault("servers", {})
    data["servers"]["perfectrag-tools"] = {"command": "python", "args": [SERVER_FILENAME]}
    mcp_path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return mcp_path
